import mongoose from "mongoose";

// One row per triage request. `requestId` is generated by the CLIENT (the
// WatermelonDB record id on the phone, or a uuid() in the web app) and is the
// idempotency key for the whole offline-first flow: a device that loses
// connectivity mid-sync will replay the same requestId, and the unique index
// below makes that replay a no-op instead of a duplicate clinical record.

const predictedConditionSchema = new mongoose.Schema(
  {
    condition: { type: String, required: true },
    confidence: { type: Number, min: 0, max: 1 },
    icd10Hint: String,
  },
  { _id: false }
);

const redFlagSchema = new mongoose.Schema(
  {
    code: String,
    label: String,
    level: { type: String, enum: ["EMERGENCY", "URGENT", "ROUTINE", "SELF_CARE"] },
    evidence: String,
  },
  { _id: false }
);

const triageResultSchema = new mongoose.Schema(
  {
    requestId: { type: String, required: true, trim: true },
    patientId: { type: mongoose.Schema.Types.ObjectId, ref: "Patient", required: true },
    facilityId: { type: mongoose.Schema.Types.ObjectId, ref: "Facility" },

    mode: { type: String, enum: ["TEXT", "VOICE"], default: "TEXT" },
    language: { type: String, default: "en" },

    // What the patient actually said, kept verbatim for clinical audit.
    input: {
      text: String,
      symptoms: [String],
      vitals: { type: mongoose.Schema.Types.Mixed },
      patientContext: { type: mongoose.Schema.Types.Mixed },
    },

    // Only populated for VOICE mode.
    transcription: {
      text: String,
      language: String,
      confidence: Number,
    },

    result: {
      // UNKNOWN means the AI service was unreachable and no level was assigned.
      // It is deliberately distinct from SELF_CARE so no screen can render a
      // failed request as "nothing to worry about".
      triageLevel: {
        type: String,
        enum: ["EMERGENCY", "URGENT", "ROUTINE", "SELF_CARE", "UNKNOWN"],
        required: true,
      },
      recommendedAction: String,
      referralSuggestion: String,
      selfCareAdvice: String,
      predictedConditions: [predictedConditionSchema],
      redFlags: [redFlagSchema],
      reasoning: [String],
      detectedSymptoms: [String],
      modelVersion: String,
      rulesVersion: String,
      degraded: { type: Boolean, default: false },
      degradationReason: String,
      disclaimer: String,
    },

    // Spoken reply for low-literacy users (VOICE mode). The base64 audio is
    // deliberately NOT stored - it is large and can always be regenerated.
    voiceReply: {
      language: String,
      text: String,
      available: { type: Boolean, default: false },
    },

    /**
     * OK      - the Python service answered.
     * FALLBACK - it was unreachable and the client got a safe holding message.
     *          These rows are re-processed by the burst queue when it drains.
     */
    status: { type: String, enum: ["OK", "FALLBACK", "QUEUED"], default: "OK" },

    /** ONLINE = answered live; OFFLINE_SYNC = replayed from a device queue. */
    source: { type: String, enum: ["ONLINE", "OFFLINE_SYNC"], default: "ONLINE" },

    // When the device captured the complaint, which can be hours or days before
    // it reached this API. Clinical review needs the capture time, not the
    // insert time, so both are kept.
    clientCreatedAt: Date,
    deviceLabel: String,
  },
  { timestamps: true }
);

// The idempotency guarantee. `createOrReplay` in ai.service.js relies on this
// throwing E11000 when a requestId is submitted twice.
triageResultSchema.index({ requestId: 1 }, { unique: true });
triageResultSchema.index({ patientId: 1, createdAt: -1 });
triageResultSchema.index({ "result.triageLevel": 1, createdAt: -1 });
// The burst queue looks for rows that still need a real answer.
triageResultSchema.index({ status: 1, createdAt: 1 });

export const TriageResult = mongoose.model("TriageResult", triageResultSchema);
