export const ROLES = {
  MAIN_ADMIN: "MAIN_ADMIN",
  FACILITY_ADMIN: "FACILITY_ADMIN",
  DOCTOR: "DOCTOR",
  LAB_TECH: "LAB_TECH",
  LAB_REVIEWER: "LAB_REVIEWER",
  PHARMACIST: "PHARMACIST",
  PHARMACY_STAFF: "PHARMACY_STAFF",
  PATIENT: "PATIENT",
};

export const FACILITY_SCOPED_ROLES = [
  ROLES.FACILITY_ADMIN,
  ROLES.LAB_TECH,
  ROLES.LAB_REVIEWER,
  ROLES.PHARMACIST,
  ROLES.PHARMACY_STAFF,
];

export const DIAGNOSTIC_ROLES = [ROLES.FACILITY_ADMIN, ROLES.LAB_TECH, ROLES.LAB_REVIEWER];
export const PHARMACY_ROLES = [ROLES.FACILITY_ADMIN, ROLES.PHARMACIST, ROLES.PHARMACY_STAFF];
export const BUYER_ROLES = [ROLES.FACILITY_ADMIN, ROLES.LAB_TECH, ROLES.LAB_REVIEWER];

export const USER_STATUS = {
  ACTIVE: "ACTIVE",
  PENDING: "PENDING",
  SUSPENDED: "SUSPENDED",
  DEACTIVATED: "DEACTIVATED",
};

export const FACILITY_TYPES = {
  HOSPITAL: "HOSPITAL",
  NURSING_HOME: "NURSING_HOME",
  CLINIC: "CLINIC",
  DIAGNOSTIC_CENTRE: "DIAGNOSTIC_CENTRE",
  LABORATORY: "LABORATORY",
  PHARMACY: "PHARMACY",
  MEDICINE_SHOP: "MEDICINE_SHOP",
};

export const CLINICAL_TYPES = [FACILITY_TYPES.HOSPITAL, FACILITY_TYPES.CLINIC, FACILITY_TYPES.NURSING_HOME];
export const DIAGNOSTIC_TYPES = [FACILITY_TYPES.DIAGNOSTIC_CENTRE, FACILITY_TYPES.LABORATORY];
export const PHARMACY_KINDS = [FACILITY_TYPES.PHARMACY, FACILITY_TYPES.MEDICINE_SHOP];

export function normalizeFacilityType(type) {
  const t = String(type || "").toUpperCase().replace(/[\s-]+/g, "_");
  if (t === "DIAGNOSTIC_CENTER" || t === "DIAGNOSTIC_CENTRE") return FACILITY_TYPES.DIAGNOSTIC_CENTRE;
  if (t === "MEDICINE_STORE") return FACILITY_TYPES.MEDICINE_SHOP;
  return t;
}

export function isDiagnosticType(type) {
  return DIAGNOSTIC_TYPES.includes(type);
}

export function isPharmacyType(type) {
  return PHARMACY_KINDS.includes(type);
}

export function isClinicalType(type) {
  return CLINICAL_TYPES.includes(type);
}

export const BUYER_TYPES = [
  FACILITY_TYPES.HOSPITAL,
  FACILITY_TYPES.CLINIC,
  FACILITY_TYPES.NURSING_HOME,
  FACILITY_TYPES.DIAGNOSTIC_CENTRE,
  FACILITY_TYPES.LABORATORY,
];

export function isBuyerType(type) {
  return BUYER_TYPES.includes(type);
}

export function isFacilityScopedRole(role) {
  return FACILITY_SCOPED_ROLES.includes(role);
}

export const FACILITY_STATUS = {
  PENDING_VERIFICATION: "PENDING_VERIFICATION",
  UNDER_REVIEW: "UNDER_REVIEW",
  CORRECTION_REQUESTED: "CORRECTION_REQUESTED",
  VERIFIED: "VERIFIED",
  REJECTED: "REJECTED",
  SUSPENDED: "SUSPENDED",
};

export const INVITE_STATUS = {
  SENT: "SENT",
  OPENED: "OPENED",
  ACCEPTED: "ACCEPTED",
  DECLINED: "DECLINED",
  EXPIRED: "EXPIRED",
  REVOKED: "REVOKED",
};

export const APPOINTMENT_STATUS = {
  BOOKED: "BOOKED",
  CONFIRMED: "CONFIRMED",
  CHECKED_IN: "CHECKED_IN",
  WAITING: "WAITING",
  IN_CONSULTATION: "IN_CONSULTATION",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
  NO_SHOW: "NO_SHOW",
  RESCHEDULED: "RESCHEDULED",
};

export const REFERRAL_STATUS = {
  CREATED: "CREATED",
  ACCEPTED: "ACCEPTED",
  APPOINTMENT_ASSIGNED: "APPOINTMENT_ASSIGNED",
  PATIENT_CHECKED_IN: "PATIENT_CHECKED_IN",
  CONSULTATION_COMPLETED: "CONSULTATION_COMPLETED",
  CLOSED: "CLOSED",
  DECLINED: "DECLINED",
  EXPIRED: "EXPIRED",
  CANCELLED: "CANCELLED",
};

export const PRESCRIPTION_STATUS = {
  DRAFT: "DRAFT",
  FINALIZED: "FINALIZED",
  REVISED: "REVISED",
};

export const LAB_ORDER_STATUS = {
  REQUESTED: "REQUESTED",
  ACCEPTED: "ACCEPTED",
  SAMPLE_PENDING: "SAMPLE_PENDING",
  SAMPLE_COLLECTED: "SAMPLE_COLLECTED",
  PROCESSING: "PROCESSING",
  REPORT_READY: "REPORT_READY",
  DELIVERED: "DELIVERED",
  REJECTED: "REJECTED",
};

export const LAB_ORDER_TRANSITIONS = {
  REQUESTED: ["ACCEPTED", "REJECTED"],
  ACCEPTED: ["SAMPLE_PENDING", "REJECTED"],
  SAMPLE_PENDING: ["SAMPLE_COLLECTED", "REJECTED"],
  SAMPLE_COLLECTED: ["PROCESSING"],
  PROCESSING: ["REPORT_READY"],
  REPORT_READY: ["DELIVERED"],
  DELIVERED: [],
  REJECTED: [],
};

export const PHARMACY_RX_STATUS = {
  RECEIVED: "RECEIVED",
  REVIEWING: "REVIEWING",
  DISPENSING: "DISPENSING",
  DISPENSED: "DISPENSED",
  PARTIALLY_DISPENSED: "PARTIALLY_DISPENSED",
  REJECTED: "REJECTED",
};

export const PHARMACY_RX_TRANSITIONS = {
  RECEIVED: ["REVIEWING", "REJECTED"],
  REVIEWING: ["DISPENSING", "REJECTED"],
  DISPENSING: ["DISPENSED", "PARTIALLY_DISPENSED", "REJECTED"],
  PARTIALLY_DISPENSED: ["DISPENSED", "DISPENSING"],
  DISPENSED: [],
  REJECTED: [],
};

export const MEDICINE_STATUS = {
  ACTIVE: "ACTIVE",
  INACTIVE: "INACTIVE",
};

/** Patient app medicine orders — subset aligned with pharmacy procurement language. */
export const PATIENT_ORDER_STATUS = {
  PENDING: "PENDING",
  REQUESTED: "REQUESTED",
  PHARMACY_REVIEWING: "PHARMACY_REVIEWING",
  ACCEPTED: "ACCEPTED",
  PARTIALLY_AVAILABLE: "PARTIALLY_AVAILABLE",
  REJECTED: "REJECTED",
  ORDER_CONFIRMED: "ORDER_CONFIRMED",
  PREPARING: "PREPARING",
  READY: "READY",
  READY_FOR_PICKUP: "READY_FOR_PICKUP",
  OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY",
  DELIVERED: "DELIVERED",
  COLLECTED: "COLLECTED",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
};

export const PATIENT_ORDER_TRANSITIONS = {
  PENDING: ["PHARMACY_REVIEWING", "ACCEPTED", "PARTIALLY_AVAILABLE", "REJECTED", "CANCELLED"],
  REQUESTED: ["PENDING", "PHARMACY_REVIEWING", "ACCEPTED", "REJECTED", "CANCELLED"],
  PHARMACY_REVIEWING: ["ACCEPTED", "PARTIALLY_AVAILABLE", "REJECTED", "CANCELLED"],
  ACCEPTED: ["ORDER_CONFIRMED", "PREPARING", "CANCELLED"],
  PARTIALLY_AVAILABLE: ["PREPARING", "ORDER_CONFIRMED", "CANCELLED", "REJECTED"],
  ORDER_CONFIRMED: ["PREPARING", "CANCELLED"],
  PREPARING: ["READY", "READY_FOR_PICKUP", "OUT_FOR_DELIVERY", "CANCELLED"],
  READY: ["READY_FOR_PICKUP", "OUT_FOR_DELIVERY", "COMPLETED", "CANCELLED"],
  READY_FOR_PICKUP: ["COLLECTED", "COMPLETED", "CANCELLED"],
  OUT_FOR_DELIVERY: ["DELIVERED", "CANCELLED"],
  DELIVERED: ["COMPLETED"],
  COLLECTED: ["COMPLETED"],
  COMPLETED: [],
  REJECTED: [],
  CANCELLED: [],
};

export const PROCUREMENT_STATUS = {
  PENDING: "PENDING",
  REQUESTED: "REQUESTED",
  PHARMACY_REVIEWING: "PHARMACY_REVIEWING",
  ACCEPTED: "ACCEPTED",
  PARTIALLY_AVAILABLE: "PARTIALLY_AVAILABLE",
  REJECTED: "REJECTED",
  EXPIRED: "EXPIRED",
  ORDER_CONFIRMED: "ORDER_CONFIRMED",
  PREPARING: "PREPARING",
  READY: "READY",
  READY_FOR_PICKUP: "READY_FOR_PICKUP",
  OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY",
  DELIVERED: "DELIVERED",
  COLLECTED: "COLLECTED",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
};

/** Incoming shop work: not yet accepted or rejected. */
export const PROCUREMENT_INCOMING_STATUSES = [
  PROCUREMENT_STATUS.PENDING,
  PROCUREMENT_STATUS.REQUESTED,
  PROCUREMENT_STATUS.PHARMACY_REVIEWING,
];

/** Ready for pickup or delivery handoff. */
export const PROCUREMENT_READY_STATUSES = [PROCUREMENT_STATUS.READY, PROCUREMENT_STATUS.READY_FOR_PICKUP];

/** Completed / handed to the ordering facility. */
export const PROCUREMENT_DISPENSED_STATUSES = [
  PROCUREMENT_STATUS.DELIVERED,
  PROCUREMENT_STATUS.COLLECTED,
  PROCUREMENT_STATUS.COMPLETED,
];

/** Still needs pharmacy action (not ready, not finished, not closed). */
export const PROCUREMENT_PENDING_STATUSES = [
  ...PROCUREMENT_INCOMING_STATUSES,
  PROCUREMENT_STATUS.ACCEPTED,
  PROCUREMENT_STATUS.PARTIALLY_AVAILABLE,
  PROCUREMENT_STATUS.ORDER_CONFIRMED,
  PROCUREMENT_STATUS.PREPARING,
  PROCUREMENT_STATUS.OUT_FOR_DELIVERY,
];

export const PROCUREMENT_LIST_BUCKETS = {
  INCOMING: PROCUREMENT_INCOMING_STATUSES,
  ACTIVE: [
    PROCUREMENT_STATUS.ACCEPTED,
    PROCUREMENT_STATUS.PARTIALLY_AVAILABLE,
    PROCUREMENT_STATUS.ORDER_CONFIRMED,
    PROCUREMENT_STATUS.PREPARING,
    PROCUREMENT_STATUS.READY,
    PROCUREMENT_STATUS.READY_FOR_PICKUP,
    PROCUREMENT_STATUS.OUT_FOR_DELIVERY,
  ],
  COMPLETED: PROCUREMENT_DISPENSED_STATUSES,
  REJECTED: [PROCUREMENT_STATUS.REJECTED, PROCUREMENT_STATUS.EXPIRED, PROCUREMENT_STATUS.CANCELLED],
};

export const MEDICINE_EXPIRY_WARNING_DAYS = 30;

export const PROCUREMENT_TRANSITIONS = {
  PENDING: ["ACCEPTED", "PARTIALLY_AVAILABLE", "REJECTED", "EXPIRED", "CANCELLED", "PHARMACY_REVIEWING"],
  REQUESTED: ["PENDING", "PHARMACY_REVIEWING", "ACCEPTED", "PARTIALLY_AVAILABLE", "REJECTED", "EXPIRED", "CANCELLED"],
  PHARMACY_REVIEWING: ["ACCEPTED", "PARTIALLY_AVAILABLE", "REJECTED", "EXPIRED", "CANCELLED"],
  ACCEPTED: ["PREPARING", "ORDER_CONFIRMED", "CANCELLED", "EXPIRED"],
  PARTIALLY_AVAILABLE: ["PREPARING", "ORDER_CONFIRMED", "CANCELLED", "REJECTED"],
  ORDER_CONFIRMED: ["PREPARING", "CANCELLED"],
  PREPARING: ["READY", "READY_FOR_PICKUP", "OUT_FOR_DELIVERY", "CANCELLED"],
  READY: ["OUT_FOR_DELIVERY", "COMPLETED", "DELIVERED", "READY_FOR_PICKUP", "CANCELLED"],
  READY_FOR_PICKUP: ["COLLECTED", "COMPLETED"],
  OUT_FOR_DELIVERY: ["DELIVERED"],
  DELIVERED: ["COMPLETED"],
  COLLECTED: ["COMPLETED"],
  REJECTED: [],
  EXPIRED: [],
  CANCELLED: [],
  COMPLETED: [],
};

export const DOCTOR_AVAILABILITY = {
  AVAILABLE: "AVAILABLE",
  BUSY: "BUSY",
  OFFLINE: "OFFLINE",
};

export const AUDIT_ACTIONS = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  FAILED_LOGIN: "FAILED_LOGIN",
  PATIENT_VIEW: "PATIENT_VIEW",
  PATIENT_UPDATE: "PATIENT_UPDATE",
  PRESCRIPTION_CREATE: "PRESCRIPTION_CREATE",
  PRESCRIPTION_UPDATE: "PRESCRIPTION_UPDATE",
  PRESCRIPTION_FINALIZE: "PRESCRIPTION_FINALIZE",
  PRESCRIPTION_REVISE: "PRESCRIPTION_REVISE",
  PRESCRIPTION_DOWNLOAD: "PRESCRIPTION_DOWNLOAD",
  PRESCRIPTION_SEND_PHARMACY: "PRESCRIPTION_SEND_PHARMACY",
  PRESCRIPTION_ACCESS: "PRESCRIPTION_ACCESS",
  PRESCRIPTION_DISPENSE: "PRESCRIPTION_DISPENSE",
  REFERRAL_CREATE: "REFERRAL_CREATE",
  DOCTOR_INVITE: "DOCTOR_INVITE",
  DOCTOR_ACCEPT: "DOCTOR_ACCEPT",
  FACILITY_VERIFY: "FACILITY_VERIFY",
  FACILITY_REJECT: "FACILITY_REJECT",
  FACILITY_CORRECTION: "FACILITY_CORRECTION",
  ACCOUNT_SUSPEND: "ACCOUNT_SUSPEND",
  CONSULTATION_CREATE: "CONSULTATION_CREATE",
  APPOINTMENT_UPDATE: "APPOINTMENT_UPDATE",
  APPOINTMENT_COMPLETED: "APPOINTMENT_COMPLETED",
  PROFILE_UPDATE: "PROFILE_UPDATE",
  PASSWORD_CHANGE: "PASSWORD_CHANGE",
  EMAIL_CHANGE: "EMAIL_CHANGE",
  PHONE_CHANGE: "PHONE_CHANGE",
  FACILITY_UPDATE: "FACILITY_UPDATE",
  FACILITY_REGISTER: "FACILITY_REGISTER",
  DOCTOR_AVAILABILITY_UPDATE: "DOCTOR_AVAILABILITY_UPDATE",
  NOTIFICATION_SETTINGS_UPDATE: "NOTIFICATION_SETTINGS_UPDATE",
  MEMBER_ACCESS_UPDATE: "MEMBER_ACCESS_UPDATE",
  NETWORK_UPDATE: "NETWORK_UPDATE",
  TEST_CREATE: "TEST_CREATE",
  TEST_UPDATE: "TEST_UPDATE",
  TEST_RESULT: "TEST_RESULT",
  REPORT_FINALIZE: "REPORT_FINALIZE",
  LAB_ORDER_CREATE: "LAB_ORDER_CREATE",
  LAB_ORDER_STATUS: "LAB_ORDER_STATUS",
  MEDICINE_CREATE: "MEDICINE_CREATE",
  MEDICINE_UPDATE: "MEDICINE_UPDATE",
  INVENTORY_ADJUST: "INVENTORY_ADJUST",
  STAFF_CREATE: "STAFF_CREATE",
  MEDICINE_REQUEST_CREATED: "MEDICINE_REQUEST_CREATED",
  MEDICINE_REQUEST_SENT: "MEDICINE_REQUEST_SENT",
  PHARMACY_REQUEST_VIEWED: "PHARMACY_REQUEST_VIEWED",
  PHARMACY_ACCEPTED: "PHARMACY_ACCEPTED",
  PHARMACY_PARTIALLY_ACCEPTED: "PHARMACY_PARTIALLY_ACCEPTED",
  PHARMACY_REJECTED: "PHARMACY_REJECTED",
  ORDER_CONFIRMED: "ORDER_CONFIRMED",
  ORDER_CANCELLED: "ORDER_CANCELLED",
  ORDER_READY: "ORDER_READY",
  ORDER_DISPATCHED: "ORDER_DISPATCHED",
  ORDER_DELIVERED: "ORDER_DELIVERED",
  ORDER_COMPLETED: "ORDER_COMPLETED",
};
